---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: appdata
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-drew
  resources:
    requests:
      storage: 100G
