# https://github.com/sct/overseerr
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: overseerr
  namespace: media
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 2.3.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 15m
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  dependsOn:
    - name: ingress-nginx
      namespace: networking
  values:
    image:
    # https://hub.docker.com/r/sctx/overseerr
      repository: docker.io/sctx/overseerr
      tag: latest
    env:
      TZ: ${TIMEZONE}
      LOG_LEVEL: debug
    service:
      main:
        ports:
          http:
            port: 5055
    persistence:
      config:
        enabled: true
        existingClaim: appdata
        mountPath: /app/config
        subPath: overseerr
    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        annotations:
          forecastle.stakater.com/expose: "true"
          forecastle.stakater.com/icon: movie-open-check
          hajimari.io/icon: arcticons:overseerr
          external-dns.alpha.kubernetes.io/target: "ingress.${SECRET_DOMAIN}"
          external-dns.home.arpa/enabled: "true"
        hosts:
          - host: &host request.${SECRET_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
