ansible_become_pass: ENC[AES256_GCM,data:U0pUG5ewu0rMaFo=,iv:lgJOgLC01oUeLZhlm/b9XNZQ2VAMF5dQ42rKXY4vboQ=,tag:IJzlV9J3hd0MWxE5VvBHnA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14qjsyp5phs3ar2epq4rve57sdc08pj3w9ayvgmntj4pwd6q8ncestmxgrz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNMUJFWUdYdVNxTTdvWjZU
            TjdaWGpnTTdUOXpaUHBRekwvUzZhOUt2ZWdjCkZuTjBoV0VwelRIWTRRREFoRk56
            bVVNRUFpUmtBMXJ1V24vbXpwN2djSTAKLS0tIHpMNVVpelNuRjFDWW5tWkpjVjli
            MDdLeXVLNkZZR1JEUjlYbWhwWmlTRzQK0NlTKZ0WGQtTRNFT5ahHwwKKhMV+hsC8
            g/SevW/e1MEMOKbKOW4KLlK9ELFQo3GlxV6B4BZTEs1A/ckN3IZijw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-08-04T03:41:02Z"
    mac: ENC[AES256_GCM,data:/HnAipnXT/CF4V0PKR9ll1xwWe4Gf8oArLf2AOMOP/JQM6vkTG5oUYn4sbvY1OREwXU9rUF4pUWdgkSpZrVp5v+Ugmee+bbeYUuLQot8Rxj8Dbh35xbPrPM+ip1Qec4/UeEZsuSdFc0+4QgQagN4naqe+qNov5289L2eXL2+7Zo=,iv:UB23S/J9QmuI8WmkL4LG1MN4DiJZDHHUFGhfsdqkRYw=,tag:3Zu3bLo6bNBfPTxMJG+Z+Q==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
