ansible_become_pass: ENC[AES256_GCM,data:D6TsyH9nQ62zQX0=,iv:1E88ythPqtDblEAxLajAD4EgoI2Bqeck/k44fYmPYjU=,tag:suAL3LhqKJEiys6doEApWQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14qjsyp5phs3ar2epq4rve57sdc08pj3w9ayvgmntj4pwd6q8ncestmxgrz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1TFlYRE9TL1owc01kWVpV
            K1lZZ1RQcys0Q1BRWXFidlNvelBhMEp2S3pZCnE0OHBLdGpWckh3a0pjU3ZJVVl2
            VHVBMGs0YzJHc0tteDFlSkl2SDI1eXMKLS0tIC9Rc0NKVzhKTVhtQ1JyRXJGTlJp
            UXhpU2krRUE5Z0hUNUl2eis3Z01tZFkKvscIgj8zJoCY9U/9GyfJR6qnGE1II9B4
            RFOl0usjyjqcfGI0hfBI+8Mi7+l2mtlAHseEQYWtXZANGCmEeKIl1w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-08-04T03:41:02Z"
    mac: ENC[AES256_GCM,data:smmhFWPTRuF7L8GlJAo7cgMdbBgsUELjAWaho0BXzyPuGG/+7hwuFMOdF11AP5/e+GZpb+T+Yfsmx7mWlH/qLudBIVCAOmjPPqb8uqvEqRFlKY0IGPewbN6pD6LBgpwcfq3BaKvut2eNkPkpIMGUkalbh/buk8om2HBpf1l+QRQ=,iv:W0cUKtQjkfBwvEYGIfwnTXCc1UgVhOcnCQsQ6gSFgR0=,tag:XH+fjldNUA87vjkyuPfdbA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
