ansible_become_pass: ENC[AES256_GCM,data:G/WzuQQpZ2nTBGo=,iv:Z6grn7sLvd/yr2TgHZ4D7T//mV9bMh9wi2qOtfpcZxE=,tag:r+OOwhpAAUVAsgo1JFHfTw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14qjsyp5phs3ar2epq4rve57sdc08pj3w9ayvgmntj4pwd6q8ncestmxgrz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVSzZQVG1wRjBoVU4vMktT
            RzlFQWJnd2V1L1Z1MkpDVkl4alBsS05hTVJNCjBtdUpGVnRDZS9kWDQ0T0N0K0Ja
            T3hhbGQwTHBXNUVCYnlLaXNuNFBHVEEKLS0tIG14TlBVQWhsTVRzU1FMRHgvZ3dk
            SVEvMVlIZW9IQjBzcDlHQzZ5K1pWYXcKm0mx5oStN4Tc40FhChnyBdk9tuo3lY12
            fTg0Fe6EaHkCRf0Hp3Kw2AtYJ8EdjYDsqfRm6f/zzABjoDO4xVO2zw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-28T21:20:23Z"
    mac: ENC[AES256_GCM,data:dCvU1CuwRBX6TpEHNOYAyf3p8bWYpKUtE+acLngkZIzAd9Ud7HZRnLo23VBpRww+OSMQcgi9X9aCsov3wPRSCvjmLb3k4l4ycaJby0XEwE29PZcBUx/PBKuNEwcGRdSy5MQGPEtsKgS58iLxLNf/RjmQewUbf5TNHpW897/6jNw=,iv:w+MPt4LkImOgedVTQ5ePFE56Y790mbdymYRsiLUz664=,tag:WUUm+nQQgVArvUlarWSqlg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
