ansible_become_pass: ENC[AES256_GCM,data:1XI9F1xtGsasTpQ=,iv:VVgSpZfjM0avgZQAuc4LqNLfmvHYtZvbYR3+Wazu3UM=,tag:10CG5E+DWKUDP2cbdXkrjw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14qjsyp5phs3ar2epq4rve57sdc08pj3w9ayvgmntj4pwd6q8ncestmxgrz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6VkovUnBNL0JoSi90TGRW
            NnIyWUhSWitqcTFJdDJ6Z1VSdlZpM2hWSWdBCm5GUlhUS3BZVDNPNStZQ1Jxb3Vk
            RjZZZ25jTjBNbkZtek4zbkRFVmNpT00KLS0tIEk1bzg1bmJhL2xVYnBUcmluRWFG
            L1JPM0FabXFWMXFkNVViL1BhMkpoeVUKNK2mXhSAE46pgdIxjKMio9Uj1ZMtVwJW
            FFFYsCeNak54E8JUbRdqZd/2mGaYl0j1to5teAhFXxPukQjA0e13Kg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-08-05T00:14:03Z"
    mac: ENC[AES256_GCM,data:8ByGeeoheg/97aLHNRcp0FOuEovKIFto2+xAhcjDv5Jza48kF3tRVywSAdoaFY7JVPGrgw6YpGyt9sm00mOy9wuwQanbZ+01zCl1S3Tu25wal70WtbpUEzlBQeaxZQRUB5bzoOTG3aLyMG/nztG+bQI8NRtA7gCDX3GXkQAY+is=,iv:jpF6oNEe7KdKwILoXtaVl7PZOJ9Wx68hEjYL4V/H7Tw=,tag:yTQBdSuK44tC1VUjrbB0QQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
