ansible_become_pass: ENC[AES256_GCM,data:VOUTlSR9rRvFWe0=,iv:a5s5Gmjejp1IbBFc67aiUPQLzcSoM4v2NYsLpuGB5mo=,tag:9fOV+O2PgGKOg7Pud4o3JA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14qjsyp5phs3ar2epq4rve57sdc08pj3w9ayvgmntj4pwd6q8ncestmxgrz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOa04vSFFYcW45Q3RYeXc1
            L0E4M2RYSUlHMFMwbTJwakZ6SFZwS2MyR3lzClc2Uld2TlVCSTJ1aUM4Rm8ybEh1
            SDFpdytXdElSUUVDZnRnWjJ5M2R5a0UKLS0tIGpZK2RJVlJXUXpwOS80cjh3ZkRN
            S21XWXJuc3BUVmdJREo3amIxclN2d0UK+yIl5B62JCD3yXZ/P8QHrF18mwWEY+MP
            txIZRu1ZhoM3zk7ynSyHNRGqDsjRcr7F43hiUhmwtmQyfa+pCGCmDA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-08-12T16:42:28Z"
    mac: ENC[AES256_GCM,data:QqepcSFDucwLtC2TdWoLBBU+EihVPLAzZWfO6s9IZ5Sz1FPEAX4PFezHa74Rys7Vi5F3r9x/WcXWcfeocJ/R/FuC78b4VAY1wDzcGtuioo2Qt3Bm/aZaVHnZYmnElHhlvcQAwZWeXsyUkRfvI9sUzYsEMAdiKaDYx5nyAWRzWGE=,iv:7DTYUt9mSeEvTwrYt6Zvwg6d4pBXoJsv7AtMNIqVrWA=,tag:1C6IOaKpCn6rAttLwPLxuw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
