ansible_become_pass: ENC[AES256_GCM,data:/E98pFZtCkXDvF0=,iv:hLtgxxVJeDzoqV9542fTvuw5PqzFbL35gyu33sy+LUU=,tag:tz3ijXfyDok2VJpIGxvx2Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14qjsyp5phs3ar2epq4rve57sdc08pj3w9ayvgmntj4pwd6q8ncestmxgrz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTZ0s3dlY0ZnJ3alI3UUJv
            T2x2aVYrREppb080a2dVQkZLZExBbXlNUFI0CnUyOGpVdG1Pc0I0WGNlYkFReDAx
            eFVYL0pxM2RlYWN0Ym95Q28vNUFybncKLS0tIEcyaWRUdzdiRVpuWHBPV2h3ak93
            bXpuUUJPdjlpeUpxQmpWdmNzclZqbWMKcqpdSzm+k2mjsBTQUlZnjU/lWEjBS4Vr
            KW00MIJC6nOeBjNZwfL9FA8zrIvoL8KIN58CJPuZOVJCSoA5+yX2Gw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-08-05T00:14:03Z"
    mac: ENC[AES256_GCM,data:QMKTEgRwcjJa3B3QCCJr09IfD9n6StEyAzqh/klAZEqG5fjTJ6qpDNEtEjFuHW6uAT9limjqQqE8siSa0Oks4wb1CHZiGn7k7fiT91ZB0YqhlksWfysYLpFWc5VQzX1zORweeg8NjjDEo2WAqFHH14uouLO81dw0MobGqglyL/w=,iv:WeKK+xobjxI7cASS+7xoOtq0EtLt21Z0R53wVijTa+E=,tag:3IEtGMzvvgVT0LGJd9LR2A==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
