ansible_become_pass: ENC[AES256_GCM,data:YEPvuy5S16GV8B8=,iv:J82XI14U8X6dr47R3Bmh3RTdmBh1gWmNnfmNKGxbSag=,tag:m3nXmbSsCkH07pKpS7GoLA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14qjsyp5phs3ar2epq4rve57sdc08pj3w9ayvgmntj4pwd6q8ncestmxgrz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzeFVDNDFJWUlCam9mWWFP
            SnNoeEZvVVNjc2ZRQTd5VmN3Uy9zTEovclNFClBlN09oUlAzS1pQd3FZcHhIZnlY
            Q3hJR0RRZE5TL3A0VVREREdUWmN2ZGMKLS0tIFZPU1QzUHlkcHFSeDdhZXBaSE9m
            dEhHVDdCeGJoc05heG1NcXY5THNKY0EK8CAsHuIgSp4gtxv27OMW02A+pNFYK4v2
            uIyhfo3PuKsMn9OxX5JYVqtHYXG4Weku7GXQgz6QELSEvMxZmwFDbA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-28T21:20:23Z"
    mac: ENC[AES256_GCM,data:xeCsUAko29XWifYlGPalfwTvv0dtGqjze4xkZXoKLgnq7wNSZ6VYO7MqBbyRyeaxzMIurdNYhZ6eBxvQiB96ija8/P5YDvL++scwjDvClSug6mzX5A5rQQ3CRW3xXxsWhvdfneWYo0eUGwf9I1ZrBKc9QUyPrtysbc4ahAnD9Kw=,iv:WEmqcxOkwWMtGGgPRxasc4ZADlr6YgEg8gJTL6rwGrg=,tag:37lykDYe2E8IXVs5d24jtg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
