ansible_become_pass: ENC[AES256_GCM,data:qIk7p85alMnUMo0=,iv:cu/5ThEzCjguZxPHUpe1oSb4SXl6lV/NrX7arzUI/QY=,tag:0ieSnTi8NFS7qfnWbruvmQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14qjsyp5phs3ar2epq4rve57sdc08pj3w9ayvgmntj4pwd6q8ncestmxgrz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwaDBVNHFMbWcvcTZhS1Fu
            TUFvYlB2emxxUFBrWVVaTmdlK29WdzRlK1Y0CnhndzFrM3kvbkhIRFp2NjYxQlIz
            VjhrYnNFOTNzWTlaQjlPNW1JZWtLUUEKLS0tIDFnMUs1VERZM3I4MzV4Q1VaMWc4
            NnRuQnpFSnMvRFArRHFTOGdBRTBibkEKatYkqfywHYKl1wSAcOdDf+8epmDLojpR
            gFwo3J2rXBeU9vnM5o/dTqrX1pwH1ug1w8t4G4ecQ+skdtCBMSREFg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-08-05T01:52:18Z"
    mac: ENC[AES256_GCM,data:FHPG1Lq5aielEJOnonmwCiUbiX2Prg1+YLqie8iQ7gCU2Fk4m/a05r413Es8bUcvFJSILx8GQtRtUJzFHOoIheqpdrQq6C5oz+xPhd+ENfbi3vUTuk5MWXyFty4L4CNHD7NCIdefGL5VGxax2nnN3h2oykBy7mg8hUl2r0kYXQA=,iv:UzvPIncNtNTSEYojbLHF0OSsGyHvL8ECU4Oi9eGOFok=,tag:lXUChLisu5qQs2JWmCEroQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
