ansible_become_pass: ENC[AES256_GCM,data:cQ4DHBFTLDw44tw=,iv:0Qcuxi9JPoLaPYKnD6Ezgay3sZy/j235q1D+z+F8NEo=,tag:4Gxp0HzHN9n3yjC5iU9Yvg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14qjsyp5phs3ar2epq4rve57sdc08pj3w9ayvgmntj4pwd6q8ncestmxgrz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDbDBabUVSZXhZa0piL2Nr
            WWw0NHcrOFZ4SkxWWU5SZWNqelFBbngyWEVVCnk4TzFoR1hzL3hHT2Q4cFpJQURl
            aGpINWdwWWhkQzhhQzJOZS9VMUZDVVUKLS0tIE1EUzNKUW5lcjRRcHYyRmdVYk5N
            bnFISVVZaVNOSm9qMGwvVE5tSWFnYzgKwJ6MRIdLe9UdH1s0erOFGAp4L9mtpBJc
            fLlzHge9myeGBWpMUVzurIdXJSfKLtL3u+fugScxu2O3XBC8mw37Yw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-08-05T00:14:04Z"
    mac: ENC[AES256_GCM,data:l9vtflG38EOJNc8gwIVRlPcfuCr/7oJkZ5clStzRS+1O8H0e4B1YPfjzgnX27nlYvGxlEtb8YytAlA1A/eM6vxX2lFROi730PsoLYARoWZhs6nsN3xOzvcwD/8l1CPHaH3VMoyBb+07IVMgyaxhLX9ttu8t975yaOOM6xzh6w8M=,iv:9561ywOhuvNA+PgSs589T5X+HhoKKyKK9jtTR8JEji0=,tag:APWtEIT2hI7CxSzF0IKOYg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
