ansible_become_pass: ENC[AES256_GCM,data:ao/RpFLBBaQqloA=,iv:pBrWtRS/+HAkDD6vu3o9TkNcEIwGG7ZzPU27tYWhQRQ=,tag:2g9vY7HbDTBZ9ioyEq2aOg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14qjsyp5phs3ar2epq4rve57sdc08pj3w9ayvgmntj4pwd6q8ncestmxgrz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXWG1NSTJYSVNBNnlydmtI
            Qy9udWJ1OWhnUGpSRytYZnp4RGRjN0Vlb1ZjCnM0b0F0TUtHY1FENFRQUTQ5RUxL
            akFMMWY1bTVaVlVGMTNwVU9XUzBEWkkKLS0tIDBnU1ZnbW1aQXZmWHdNMmJxSlk0
            MTFPd280WW4vRWxuZFVDV0NuM0d1aEUKV2ES18HBOsjEGXvu0zxs3yh1cjJVyhOx
            y+rmCbS873SjWwqhfem20PvfYbDMkv63thI3W5IeQjZmA4UnOjK+4w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-08-05T02:24:43Z"
    mac: ENC[AES256_GCM,data:keNx2BKSRd3PvMTumH5eBnZZCx64s0PB55nCXftL4RD2N/XLsLAzioanapTb9GpIKtNRYv/zhjissLxIWY+lEWNKz8B7SlyesUxxtRhNbL3dDcQ/f82Uj8PamlUP2X9Jve8MSwUp5ISGsU2IaHBJZ7utsrbfSEEfoe6tboLXKTY=,iv:ISe5+k0VFnQCioJ5cNV15pIe5qblYxr+GLg2+R1L4MU=,tag:SSb+iZ9MceXoYpW1EDKOHA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
