ansible_become_pass: ENC[AES256_GCM,data:7YcdY34DyLwsX3E=,iv:sYELQSl+LUftPkYThxuBmognyA0MNqk8Mr1USLjZLbI=,tag:Ou1gmFwm6/rdQn9yfuRTVA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14qjsyp5phs3ar2epq4rve57sdc08pj3w9ayvgmntj4pwd6q8ncestmxgrz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBORjJKQlFib3A0YVVlcHhr
            TmJiL0pOaDFYODRnTnBydGdhOWhuY0wwTWhZCjRDRXdNclhZSkcrY3l0ZFFPQkk0
            SHgwaGFTQ0Rwc3ZYZ2Y2U3Z4UGh6S1EKLS0tIDVCVVpiUldleGQ2bkgxTThwQ1A4
            eVJGdWdLWkVNTDhxbS9WRXJzbG9teU0KH8QBzoHDxTOWzaCqq5h5ATMsWw2R+qFw
            e7xhhBm3PEXmGcJBQ3CB+C/yQciXMBUyNO/M1JaYXyj5tK/AUQm4Gg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-08-05T01:52:18Z"
    mac: ENC[AES256_GCM,data:lA4SRv3Z3PcRpDBfBmfMW/YrY370ze2Q/hFkXhKeoaVGx9iioA2Aikn3IeNsNLyZXv76RYhcFpqbhCK99MYdhqTIEMyBlTpqF3HjErdTaAhzR+BVYWNd+2v0xDvH98/7LlMBvRZc2gNMNPBzmywX7eCyCS/gaNy3k+QMeFWWd3o=,iv:8anpdbpCmZt3xpZL6E7gqDkwGdqtaxO1IzxSvBPQeOE=,tag:3QDOuAVr9FFVciY7aL3sog==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
