ansible_become_pass: ENC[AES256_GCM,data:Xrpsor+svWsh478=,iv:LB1jeRug0BVrabky6wlx8pn9h+04XRXII00QtDRK7xg=,tag:P4R8m35raUKCk1PUgkoKVw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14qjsyp5phs3ar2epq4rve57sdc08pj3w9ayvgmntj4pwd6q8ncestmxgrz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEMHFOMGxET3lKbEdKU2pF
            WDdNTThraWNOVkpHdkRkYk0yVWhWSmN2NGhZCmxJU2psVlowTklBSGl0YlVnOUFn
            bE1GTkF4Q2NWSGZpYkxCVFFIcnlLWGcKLS0tIG5iakhNenEwQlc2Nys2WStacnJy
            OUhRMGxtY3p4Z1FZbHFCQVVvcmF5bFkKJdZXdi5rwYh04awUObAEEuJ7o1aehvgi
            IFJQ1Pg77n1K7sJpJ3IEVOXx6Y9qXNm8j7GkoOymvs9iVQDrKOznJw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-08-04T19:47:43Z"
    mac: ENC[AES256_GCM,data:n0CCrgT7ZBQFevcvuwToR7mFu4GQKpB7+zZWNh1M+NrR+ZXZ4y6JK6pm4EgGeW4LgqTWPY+x8jQPMLBrzaL6KwExiXs9tiMmEHYT/JXuEwVx9N2c/B7CzDSOyeWqjdgr/hOVNFon/FQGl4yqLDHyF3KISk5H9AmNr8vgMFgtd+w=,iv:mJikrqSer9VC7o2INShgpZbAPKP30FrDyEEaDgaA6WI=,tag:it1E/4sDaYK7sX2wQGychQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
