apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin-secret
    namespace: monitoring
stringData:
    admin-password: ENC[AES256_GCM,data:Gki6fkLRLwDWez0=,iv:UYFE1EWjgKeaUYpcqyRpUQ+9mK3xj/Cd4MPhj6VZmfg=,tag:bwSe/hQbaT9Fo7Rd1P1Sbw==,type:str]
    admin-user: ENC[AES256_GCM,data:Nb/ROgI=,iv:wda9Uv+PR9Fi6+69291oFvIhSM2cuqw5/2YoVxfkryc=,tag:61Mn4xng7PrF31pSxRTPUQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14qjsyp5phs3ar2epq4rve57sdc08pj3w9ayvgmntj4pwd6q8ncestmxgrz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTaVlRMnI5MFp1Yi9qTlhn
            eWtLSDhlV0JBdGYwOSt2MmJ1ZmNTZE1JNmtnClhOSzRBd2MzbThXWXNYdzlTOWZi
            dytmKzhxcjNidVBibWZPWmpYclRUYjAKLS0tIDVlY0gydllGTU5JTGZQdkJhOGhM
            a3NYL093b2tZRXZpS2ppWW0xSHBwVm8KuXGqDXKWyK2OcRyM+fCDUPD36ANSfQ3Z
            BJs2znc28kdFh3UrBXftB/hMZPMY5ftM/iEbB/SonSn9iQNvwsgYOQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-29T02:13:27Z"
    mac: ENC[AES256_GCM,data:Qy7lVcCFIsXTOJFJbTeXp4zRPDzxssc7zCGOQLlVjiCrYD2aCrwA5Mfe7S0nw4GSoz+N81FAwXsDU8BdAgEH3VCQSVRq4LD2vPvEB82DGXk08NaVoTg7uvs2mqrPY8DxDp4jQZS5Fm/9iDejnaipsr0JT+yYkujkgM5urFlBm0Q=,iv:eEZAHlwFHvgwlgruw4G+o36szS0Ocd8o0sG7kl0hYVg=,tag:Lwq+M6uZuZjU9TsKGZMwcw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
