apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin-secret
    namespace: monitoring
stringData:
    admin-password: ENC[AES256_GCM,data:bFAacpurFaJQBFU=,iv:vCvIZwOE+/IC1R3KbcpPmJOBYQHW7kobgr7eOwjxql4=,tag:yk6yvauYa3VVWvlybf+9bw==,type:str]
    admin-user: ENC[AES256_GCM,data:e1eGJFM=,iv:KAtWqIO2jKRA+6ng9T+I+IhA/fMLzWQ3ipJomMlAl+I=,tag://+YKGVygq4Td9/5S94sSw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14qjsyp5phs3ar2epq4rve57sdc08pj3w9ayvgmntj4pwd6q8ncestmxgrz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIamJDUGkrRmpya1k5aDhz
            a1BidEh1SEdnaTVreWIwU3JxSlJieWpRMlg4CkhwWmx0NFhKL3pwNWJBaW5jKzcv
            Sy9sRllLc2lTUmJFdEFTdU5mcnlYODQKLS0tIDRUbmlYcmVVR1ZaSGkvYXpwQnFN
            OVMrMHNiaDVqUFJqSUllZm5zNzlqNVUKlzy2/4hC8uoxa1bXxFxQ5IiLyy1lOyif
            8O2LBek/NCgGrRG7n+/Ze+NpQw6k/y8EiYUaSoHoKzO2kxaJKhjY7w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-08-05T00:14:51Z"
    mac: ENC[AES256_GCM,data:8/y7p+F1Xy9eKqy7b8q3pPH7zdWz36p9djHJn+ZauLqBTcbJerI4M1ts1dd2Lce6BbZB9VBVZQtveAy+Kibqu+QJLCcHyGFDpMjuRgOheYxtAeRJjYyoWZzwWAlVDp0sBwdsmgvCTDRv2ToNi0/yp3UeEqUNwtIs7JPz4KOK6qo=,iv:j3W9JgbXZJfGcNG2EJQC3gif7zzaYlymu06DbV1AMgA=,tag:Upzb5F+06WgK7Q9/MLPymg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
