apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin-secret
    namespace: monitoring
stringData:
    admin-password: ENC[AES256_GCM,data:jUOpCxDgh/8f3qo=,iv:5Ox2D3VPTPGNtalNjc+ruWb7a3sXycrEVVmuO0PIZqk=,tag:3lXu3/eENZPOGp0UQjzn5w==,type:str]
    admin-user: ENC[AES256_GCM,data:quGrKRA=,iv:J5cb8RaBDif2D6H0H3/56UgYpi+wiodbwPUNwk0oBao=,tag:3j3HkyDaH4ym4hhFWyHOJA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14qjsyp5phs3ar2epq4rve57sdc08pj3w9ayvgmntj4pwd6q8ncestmxgrz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2ZjhNYzVNckN6alErdzZ0
            V3hOaUQvRUYvMlUrTmZSRzMxVUJvZzdJSHgwCnRqZmttRzFPY1RRMVpNMThKZmdz
            UFpFMHlFcXRrOWMrNnFySW5nK1VjSFkKLS0tIEZxL0VMa3lMRFR2OWhxRmhHN0Ex
            aFJIUUtmUWViSURlTlJ4N0FkZEZFL00Ky5FZ9IXJaQ4mo1naQszQRHNy8lchIEL5
            n2Jh2VfrOi9T76ADSyX0abdlA19Z+oUttXrmNFdgnP6Hxib8FKgj2A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-08-12T16:43:18Z"
    mac: ENC[AES256_GCM,data:o/7yTMB31BQ5vIfYwNpKtRbDsDE8vDLLkqswsFGGUJrJ05I3mEMSWvmGoM83cXPq1fwI6HAA1/ztJI2zWqfArhI0+wg3nImmRidJM2U3t8143cZHN+hftNN99dwPInn50SwTr9c7LTWLsFkECelJ76IQTIbj4eXW1fkeXdqVW8Q=,iv:jnyESoQHEL7ube0Take8e8vZD+/YdhxHssXKgdg8P4M=,tag:Rja1V8v0WHyM7Hvdc85zMg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
