apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:PL2si5U1SnKhmiMzYxOkI5Vpl7tStj1R,iv:lbr5tHLgmy3Xs+4mfTLCz7O8ZdRvfq5H0kRQWvyJjT0=,tag:julAqpigWjDc24vu/2uhUQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14qjsyp5phs3ar2epq4rve57sdc08pj3w9ayvgmntj4pwd6q8ncestmxgrz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQaTJ5M3VKSWtMdnVMelNS
            QVY2Qzg2RCtyQTFGd3dLalFZbms5L0YxeG1ZCjhmZjhrLzJEbHF2bDR1MVBZZGV2
            eXdIS2ZEVDdqUVBZWDl1S3QvZGFXL1kKLS0tIFEzWDYvNTVRLzRLYU1NZnFOZVpB
            anp3TUR4U1NBdjJXRVp5M3lXZXA0QmMKfTyVQ66ACMiK3ARaN/LjEyxzt6cwJNY5
            YcXwALUeWBHC4VUc9nAzDZ1og5JHzduF9boUSuXHxhS/+yHVPMxByw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-08-12T16:43:09Z"
    mac: ENC[AES256_GCM,data:ZeNyG6MucNC/QFETfa/6mv1THyF+CDFRqTNuZpAamjlu7JBjuTI8xFsE0y+6Pwv0dx9VXNAwuS+uyysWX7/A5wYdSAtqnpZlYNENJmnFLiChycuGHWe04ypXMIueGgCATEhbF+iDPPLkMbLTVoEMNPj1SD0P5ekvhyvH9Fhbh6U=,iv:C+cEg/rOFw8bNWu7Ob+vmPjCg1TwCmVysj2lb1dimoI=,tag:ZptMcLhE+i6z29XaBv5ORw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
