apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
    namespace: networking
stringData:
    api-token: ENC[AES256_GCM,data:webhYHZM9XFSxHFSFRw0RZC5ZZ7S7J5KW7a0/sUmjnqCFpjlphKIEg==,iv:vS25Oj/DsL9NCzNooYS1LXyFvpQo1DI+hsIgWEblDUc=,tag:zl/jddEpCAm9hCf24PpCLw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14qjsyp5phs3ar2epq4rve57sdc08pj3w9ayvgmntj4pwd6q8ncestmxgrz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJQzBrVkZXZmNqVjVuRUNU
            bllJNGFBYm1RNHhNVzZvZm9PNnB6aEZ4OEJ3CmpoQUlncnM3N05OaGFnNVpCaWph
            V2tTckpTUHFza2dna1FEMDhjWHpvZm8KLS0tIGpvSFlqcjZuN0RTOFk4Q1hUbE5l
            Z2NnZW12L3FnT1VBMXhWSHZNSWoyZGcKNCyyFBKs9bpNNRG8Bb83Bwa9MJb+hhJk
            bNMjv04SqhxkdFGmddglW6EocRaxW30Bk4q46TgGGNkUu/9eoBpEYA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-29T01:29:15Z"
    mac: ENC[AES256_GCM,data:MBI+J3MKzOZXVxdpF/gSEBLieFzYdRaB7FEVdJmtiFV5xyBPoaKnIYfYLtgUfFy7c4fSVpKZYuGu7RCqR/ferlCgc2NYXZe+MklkWTF4j8mzPJkUB0/Abg+YQiiIH/bO5N2YMtW59FtCL5QbUQEbAGdF6mUWl4s3K0j0PAdhaVk=,iv:egvAW4fDnt0NOtRv9QnU7rFchzq3MwFiAvMDn+icdRc=,tag:DuN75oyLtvVhBO3UdHdnqQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
