---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: appdata
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-db
  resources:
    requests:
      storage: 100G
