---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: k8s-watcher
  namespace: komodor
spec:
  interval: 1m
  chart:
    spec:
      chart: k8s-watcher
      sourceRef:
        kind: HelmRepository
        name: komodorio
        namespace: flux-system
      version: '*' # Use specific chart version if needed, otherwise it picks the latest
  values:
    existingSecret: komodor-secret
    watcher:
      clusterName: home
      allowReadingPodLogs: true
      enableAgentTaskExecution: true
      enableAgentTaskExecutionV2: true
      enableHelm: true
    helm:
      enableActions: true
  timeout: 90s
  install:
    createNamespace: true # This will create namespace if not present
  upgrade:
    remediation:
      retries: 2 # This is optional and represents how many times Helm should retry installing/upgrading
