apiVersion: v1
kind: Secret
metadata:
    name: cluster-user-auth
    namespace: flux-system
stringData:
    password: ENC[AES256_GCM,data:Y9Zuj98X15HMNZ4XYGLu1eaLD8weV/YDW/Jj5cro2224LrtF+q0B/swXWEXdp/cPG8PeaI9aE6FWrTjS,iv:Y2n45SPIcod4H3rIHNODamXIYaGmFOGWGXlPp+foPrI=,tag:SNGLOza6lGZ7wrAf4LwkWw==,type:str]
    username: ENC[AES256_GCM,data:fqPufE4=,iv:y+qNgFlbu8GAlCRuvHUgnBSDheNlMQq1jhr/JranyeI=,tag:UfhLFTysh1eSQN2dNWEHjg==,type:str]
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14qjsyp5phs3ar2epq4rve57sdc08pj3w9ayvgmntj4pwd6q8ncestmxgrz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOVUlEUFE2VVovbWNOejN2
            bmg2MTFTMmdSM3JqZnJDekZCVFRlMExJUHhZClBneTJsdU1PK2pwYm15dGZ6SWZP
            THRULzRIUXFDVTd0R0hBMHdmcHBkT1UKLS0tIDdJRXc3WlQvbkkxYXo2ZjEwUDMx
            RVc5OXlWRUZWOTVwOTN0enZPWllzV2MKCMmh8VoRZGgwaKtLsu1N0LbWzKEwRfCv
            0Purf+vVmGTkt2s+1O6Jmq8/nZ0SOepnVgTmHoIo8wm+yPXXKTh+sg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-28T21:21:16Z"
    mac: ENC[AES256_GCM,data:3AtaI+Y+0TJ/Yyn9H2fzJQgvz5EHNxLSwUs/xldzeTwN/xV3xtnYi7+poXe520/6Q8FGnU0SB4IMhHqDP2xMrWRD5I/9bdPb3kmWog3GnqDP9gRZbN42i2bavgZ7VhDHs+s489xGn9TuRaE1CxnoQV51pBGckuxwFS/xMxbtYzE=,iv:cx7patmupl2RuVdBpwhTlpMAV2NO2G9Gcpm5ybrtifs=,tag:SRNGzjcjhllbyMZ8fQ5Z6Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
