apiVersion: v1
kind: Secret
metadata:
    name: cluster-user-auth
    namespace: flux-system
stringData:
    password: ENC[AES256_GCM,data:ARVbJk5wvdVYAs9zb1vuU93rrjol5IwT2cDqczd2kXPbHOWEyPR15/Bz6+FDUOhHlElC2e4ggw698tcw,iv:zAQeHjPUcjh68aS/5tcuhLzrIjsCxh9fC7Pn4txEGhU=,tag:4fNdTxFM5dA4ufQtCyQKwA==,type:str]
    username: ENC[AES256_GCM,data:1bnCG84=,iv:mwDdBYE6ay7hPC6yIjp1F9IOoxCcVGUWweGNpW8Vfr8=,tag:uEaa7GCwEzecNO+pzEau2w==,type:str]
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14qjsyp5phs3ar2epq4rve57sdc08pj3w9ayvgmntj4pwd6q8ncestmxgrz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoMDB4d3psL1dwd0JCN1Ey
            Rmw1RXFRQVl0SE0wZFBwaURXRi9BS1UwT0VrCkxXL3hBazY1STNwUW9BcGxUZDNz
            Y0J5TGNMNVZlem9NeXpVL2dPV1VGd3MKLS0tIEM5RUZROXo0cEJFc3J2WWpqS3N6
            dnhZYXJqdHZ6cVNhdCt6aHNFSG5FdmcKb48iCYGwxb/DF86Pq+iZnK8EspjslcVj
            WvMnfgoh3RNIGJ7mUfNAua8XutX4S6gSUnyfLaJqKednK9Dsqt0f7Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-08-04T03:41:58Z"
    mac: ENC[AES256_GCM,data:V+1qkN24sbgYLb1TDs5T4pDyfKMzjB3NYhnMTmyp3e2jZOplRgoEH945vIy3fvAlWLDK2hKaaa9OxMmkUue9k5dg77p4Ee9EC6ngBNGxoa5VrMJaiMUKjEqdYsywNFeapIKLOQ0PuZ6ISZUbT0BYQmEWCi/so8bKGZLICQij+6A=,iv:eFNRNsyTJco7Dn9JnL+RQbLLJnm8T2YN0TIbC0K8wyE=,tag:suNeFLkSYP9dLCtmC9kxsw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
