apiVersion: v1
kind: Secret
metadata:
    name: cluster-user-auth
    namespace: flux-system
stringData:
    password: ENC[AES256_GCM,data:20VTR+QQtXp+avkBFu2NIhJ2wd7mTnNzB2OJNPBGToCosCPomnBq6dJxwkzWnI7Q4XNhpdfR51Hcz9+O,iv:wiwyoaCsFx1zHZVKUAoZ9eA6TTRlwbutzXNia7dJsqo=,tag:EzgEqPHCQWohbwiytEsXXg==,type:str]
    username: ENC[AES256_GCM,data:4FQ5+ZI=,iv:G1eyuTvlupwiOKTcGmYWI9NEKhA+EImoYsSPwklb7Rw=,tag:UV7JmljOHiar3AqNtvFYXg==,type:str]
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14qjsyp5phs3ar2epq4rve57sdc08pj3w9ayvgmntj4pwd6q8ncestmxgrz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzc1k1VW9oZytkWkt3b2tY
            U3QwbVVKcjFQeVkweWFEdnNGaFVCQWtoaEc0CkhWSVhCd250T2xDRU1UUDRZV3BY
            bUk5UEtrb1BCRmxnL3pWcU5FMmQ5SGcKLS0tIDlpZHFHVGNaSS85M0FtQnVUeXIv
            Y1g5THV1SldHRTZCQUUwUE9CN3ZGN1EKyqjtln5QorHHujp5Tx7q8wRthsaYkN/H
            16AHw7kGK7qzeeugt4wzCYK1mXcco5gZNV42xUfFmrfD3e7+2syEHg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-08-05T01:04:41Z"
    mac: ENC[AES256_GCM,data:R6EY8a/68JkYom5EHvw+k8XMN7FxwHVhtQqTUk+9hzES/X8mmUFeQetXft5nUWdS7mIU1Z98fjoBCwWE5EC+Cm8BIiw1MwcmvEhReyIu9y52uJU2KSpzDViTbJgoxeT/fB2yybPBrLG241vZon1TMNT+3Dcrb6CWP27TnMEmbAk=,iv:V1iOUXyhe9XBqSW2vwI4a7PchEX6tnoBTqxgRkUPIEk=,tag:Xxx9YPbAxB9KmCIUfvldZQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
