apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets-user
    namespace: flux-system
stringData:
    SECRET_PLACEHOLDER: ENC[AES256_GCM,data:8IM9MYp2YosBDJYf,iv:h+wzM7EeK+3EX/wgfWEJ2Zl/ZQBF2MBjmGsg3jI0OsA=,tag:JkmfW8tBhypilBCN0Qs5zQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14qjsyp5phs3ar2epq4rve57sdc08pj3w9ayvgmntj4pwd6q8ncestmxgrz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvRHZDVmVvUDZRcGdGS3Zn
            YS9yWFlPT2xiZGtPUDRjYzduZi91eG5KYnlnCldoUjh4V0didU5RWVovZWl5bW9o
            VVZCYUlETDNPYnI4YmdKa3Mza2JVaEUKLS0tIGJ1dmdEU3FHK3FodFI2YSthMWdY
            TW1SMDluUGczZCt0amxoVTdhU2YvczQKfI8yGKrYK2VTKpD0Jg9ZKyj8hx5g/I/O
            csG0nacxjM/VFRJ0QF9PveWKUdef+8mnH984+WJhdV9T5FL5I8lWQQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-08-05T01:53:00Z"
    mac: ENC[AES256_GCM,data:FzQyTR72KxPcw6Mu+6nzuwUCwJ1opVVwOgq5orn3YiZz11LgZVoVmZ/k17MW97OAQzBbRyLtxY9/S3rrEaWC8nOW6RD5LZ9P9NuqOHQJ4MH8QgBiprbVeqkf7WbWhjvwu4RyhW0B1DBVT4RWkesArAfTW6wMLyvmy3IdBFTBj2M=,iv:FCEKaYHb+mEBeZ8LBqc+grCoEVJ1ma2IPkDc5oLSvzY=,tag:tffkoX0WU1tCvn1TFjRjYg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
