apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets-user
    namespace: flux-system
stringData:
    SECRET_PLACEHOLDER: ENC[AES256_GCM,data:r6V7Ay3hTmtOoLrg,iv:SimJKsXh1dCBzxz8FM+DPGE5Me7DPneSc96OTeVRrTs=,tag:QrnFiw/Oe4hGyaMrVdmJXA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14qjsyp5phs3ar2epq4rve57sdc08pj3w9ayvgmntj4pwd6q8ncestmxgrz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYUUVYL2ZQOUZwRksvcmV6
            ci9teHczS2NUUzJVeEQyZCtNc0RpMEVWNVVRCnFEK2J5ZFVmTUk0RUZCS1lwNWFx
            STE0N1lIajJlUURaTGZTdForTWZJQm8KLS0tIC9ob3dzU3hUMXdzZm4vVXdnMjZN
            RUFiZUpHUWRkQzBmS2hNS1V3MGpEV0EKQmOcB+uIiHUrLyuJWiqpGfXqZ8KGg0qj
            HJbVhoYzTPWClNzkQMA/NAAn/d1QvVinfv6cE/I1xYy4oTFoZKThzg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-29T01:29:16Z"
    mac: ENC[AES256_GCM,data:SoZUHysceOI78CufmIEV1h04xC+/PqfbB7FFkq/HtvK/B1x9eFSSi/1OGxz2oVw66Qs5G0dAXtm5bOxpuY2xlayXTusiJ877o+4reQmpeQEbdCJwrvf+d9kMJVOgsqWsCmsHVCwA6A25OuPVwKrRnOL8OXHuSjn7yf4bewMGrkk=,iv:wNjomOyY/pJ9M1y4inkoa0Sv2RPrkg9TtXcEVTwCmrY=,tag:8DTjWbTelJaiC5q+3KTwMw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
