apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets-user
    namespace: flux-system
stringData:
    SECRET_PLACEHOLDER: ENC[AES256_GCM,data:rHygGbkdh9hw9BrP,iv:p7LlmgzemhbnfS9z+I2dUsBEp0P3HNpAyGnOVEtHtcM=,tag:My3JZmwGWZeRcjHE2BiB/g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14qjsyp5phs3ar2epq4rve57sdc08pj3w9ayvgmntj4pwd6q8ncestmxgrz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4SG45UUdCYVZRdW5lS1hi
            d05Qc08ybjhsZHQ2enU0VFFNTWR3NFQwcXowCnl1R0FrVHUwYTJyWXI4cDVqdDJU
            M0ExaldOcWw2R1duSWtjM2p4bmdLQmcKLS0tIG40emoxdEVQekI4d2F4MitVT3pV
            cmd0dEJZNVA4M1JQZ0xKeHB3VDVJTTAKtKy2fxAYkdPpdDW+k6MF9vS9I6Gk3vY9
            +q6KU8hLfMEgVweuzJo8THVrrEprrkwCcRDFZm4+GM1iv8b2re5gyQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-28T19:51:46Z"
    mac: ENC[AES256_GCM,data:kYcJ9oDWxMj7cV71WMeDvVjvDs2+ZQeq05ZTfEaHMlNL7qAZ3ByZaxe9gwW91cp15YizxhLJEaVveBIvJQ4jZzL2+MT8NSXpNS5XtzGihibsZ9okXpCCrmZP4rJOgoNuqQcWRR+b8hkzsvhfK3rnEFP1hplnxK73MdnEYVdayiA=,iv:IGsgHfYeKYQEbReZfvqG1aZ3PmkdrRp17rn2ZlK7X6I=,tag:ea2zmbPB1NT/mVZe2K8rsg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
