apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:diJM7NaR5NS71zQ3RhIbF0zA4HZJdA==,iv:ROCqdw8h7/tof9B+WdaVsDhsMIdS7Am6KLjwst3sk/Y=,tag:NHomgwWRvlyYeED0E7OBag==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:Ji+HPhxwqEFAcOKo93Mq3seyQzr7O+ynnlt0YtoREKZmV8lL,iv:sJWxrkPXdN1PRk+Z3wF4Q0ciZZ0mAIGmV9QRGnCy19g=,tag:I6TCdrPO8T35u69EIw0dqw==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:ob2Rn/BeEjtC+HSw6Q==,iv:Mgo/zTAN2ze/mAWUDar9Z2zAMKRR1oIDVGuviJPO06Q=,tag:OM+9sDkN6ldA+TC2eQLVKg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14qjsyp5phs3ar2epq4rve57sdc08pj3w9ayvgmntj4pwd6q8ncestmxgrz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpZmNGS0NyZEsyQXB4NzUx
            OUlsU3RFcG5ZREYrcVl3REg2Wm50V05mS0FRCnJRN0xjano2QmJ1N2dzYXpiN2RF
            ZGtEdG5ieHlDNy8vc1g5bjNxYm5ieXMKLS0tIDkxajYyMTk4SlZ3MDZsKzkxR2dL
            VTF0T0VBd1hJb3JvWlErSFkvSHpHSmMKciqvnma5jRuqNVo1sVw5+nnC70ozh5O3
            R6efrYE+H5zaRKvmQhaAcNf2dc+v3TQeWsImGLUP8UmAXDEWBPad/w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-28T21:21:03Z"
    mac: ENC[AES256_GCM,data:F0jQW7MysA8r0uTB8e1qaSaWX9BNZE+KoZ35RJqHS51smzHFZQXVt4QleXaoR/GLP0Hmc9+3prbK7bHtlUHizs2AJG4JjEN+t/pmpokxbv5KCA4SE6MyRhuySc10U+yZTAxHQUQRtKaJejPhGo1JsN+HF38/8FhuR4/Vk7Aj1e4=,iv:BF6Lp1TlB9u2uMd5K1obNJPeMIpp46R44xfx7g575aE=,tag:rkr2zWSoVenHPvw+0y41yw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
