---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mariadb
  namespace: databases
spec:
  interval: 10m
  chart:
    spec:
      chart: mariadb
      version: 13.0.2
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    auth:
      existingSecret: mariadb-secret
      database: ""
      username: ""
    primary:
      persistence:
        enabled: true
        existingClaim: mariadb-data-volume
      service:
        type: LoadBalancer
        loadBalancerIP: ${SVC_MARIADB_PRIMARY_ADDR}
    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        annotations:
          external-dns.alpha.kubernetes.io/target: "ingress.${SECRET_DOMAIN}"
          external-dns.home.arpa/enabled: "true"
        hosts:
          - host: &host mariadb.${SECRET_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
