---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mariadb
  namespace: databases
spec:
  interval: 10m
  chart:
    spec:
      chart: mariadb
      version: 13.1.2
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    auth:
      existingSecret: mariadb-secret
      database: ""
      username: ""
    primary:
      persistence:
        enabled: true
        existingClaim: mariadb-data-volume
      service:
        type: LoadBalancer
        loadBalancerIP: 192.168.86.206
        annotations:
          external-dns.alpha.kubernetes.io/target: "ingress.${SECRET_DOMAIN}"
          external-dns.home.arpa/enabled: "true"
    secondary:
      name: slave
      persistence:
        existingClaim: mariadb-data-volume
      service:
        type: LoadBalancer
        loadBalancerIP: 192.168.86.207
        annotations:
          external-dns.alpha.kubernetes.io/target: "ingress.${SECRET_DOMAIN}"
          external-dns.home.arpa/enabled: "true"
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true

