---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: maria-data-pv
spec:
  capacity:
    storage: 10G
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.86.44
    path: '/mnt/tank/db'
  persistentVolumeReclaimPolicy: Retain


---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mariadb-data-volume
  namespace: databases
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  volumeName: maria-data-pv
  resources:
    requests:
      storage: 100G
