---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mariadb-data-volume
  namespace: databases
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-db
  resources:
    requests:
      storage: 100G
