apiVersion: v1
kind: Secret
metadata:
    name: mariadb-secret
    namespace: databases
type: Opaque
stringData:
    host: test
    mariadb-root-password: password1
    mariadb-replication-password: password2
    mariadb-password: password3
