---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: choice-marketing-web
  namespace: dev-stage
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  # dependsOn:
  #   - name: choice-marketing-api
  values:
    controller:
      replicas: 2
      strategy: RollingUpdate
      annotations:
        reloader.stakater.com/auto: "true"
      image:
        repository: ghcr.io/drewpayment/current-www
        tag: 0.0.4
      command: "pnpm www:serve"
    service:
      main:
        ports:
          http:
            port: 3000
    ingress:
      main:
        enabled: true
        ingressClassName: internal
        annotations:
          hajimari.io/appName: Choice Web
          hajimari.io/icon: heroicons:photo
        hosts:
          - host: &host cmp.${SECRET_DOMAIN}
            paths:
              - path: /
                pathType: prefix
        tls:
          - hosts:
              - *host
    resources:
      requests:
        cpu: 200m
        memory: 350Mi

