apiVersion: v1
kind: Secret
metadata:
    name: choice-marketing-www-secret
    namespace: dev-stage
data:
    .dockerconfigjson: ENC[AES256_GCM,data:mJVfpnthH7UqYb1sUmQOiHlRYQFT1bC55pdlQqLYClWSGqvl8y4cIWNXRoNEOHeehCO1a3n4mL/Arq8KTlhBYBBv4ijabdaeuEuVxWEl/uEgGdJ94e+s76UijcHW4oYdAbdvdz+d2YdnF2ffnIcF9OuhVkHiFYxj4Ip9QMxKCeEGX9AHDNc8XeQbZP920txPkNRQ7wv8E4jS5DMVvOZHRbpiTQGfOZabVmfSRcfnwvCsSJcJHKQhD/HNYImSdeum9PievYxrgsVuUNXwaIw2DSe9Zgd6DqdJ4vLLvIrrfBbgnxTGpZ4PGcuZGB/knXCNqNCgVmWBpqn8m09ADxBYc3GO2qi9tGW8DHFXbdJ3JZ2H0eBUBAudyX76/rVvzbpirLBEuD0vbcshx2bS,iv:1/bBc2JoSeuL42J895IecTu+ti4/63hjegelJ2srSIY=,tag:47sblt/Srlx/I43XS+20vw==,type:str]
type: kubernetes.io/dockerconfigjson
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14qjsyp5phs3ar2epq4rve57sdc08pj3w9ayvgmntj4pwd6q8ncestmxgrz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGNDBCcFFoMzdoQjlYeUt6
            REthOE85QWN3VmV1MXZQMWxvN2pTakcvblVNCitXMFBUV1EyelFIMlBMWlRUMm81
            bCtMbXNTUDhOOGZtMUZtWm02ZllBMkEKLS0tIEtmL3BZakIyWUZPTVJCVXIrTFBD
            QzFWdmtURzYrMmMyTy9jYmpPV2d5ZUkKoI/W+kg99VeWgzsRqJS0Piq131GUZIaw
            qbFY75V8Yg2W7FSYrgk7TU1StlEhmSDKMF8kHAnwcNXn4apIlKb3aw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-08-21T01:55:03Z"
    mac: ENC[AES256_GCM,data:LyOJQ0J2UOoGyphGLK3pnaag6iZL/HMqnjlduEWeyrDOSdvVfZ2buOB+U91c5DckpDoZPFRwvoR9vu80KhIs5ePD/Ctht7hGYlwJnBW3PAgSGLZZx680na+CR/FcaK1gFMaMz4k6c4UMkJ0Atk8BcPwhLutjFVuKJD4YdCSryPM=,iv:jvxrACldl7yyUS6hipIGEgRLRIUbtxrC2O2ZI3TZhsM=,tag:odQmAdt5nnIllhj2FizQFQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
