apiVersion: v1
kind: Secret
metadata:
    name: choice-marketing-www-secret
    namespace: dev-stage
data:
    .dockerconfigjson: ENC[AES256_GCM,data:AenOYTkxgJS5QHtB4tBx7ze6TE/M5u+UAt0zexy7/GlhZai7Fq1YaI3oj+fvEq+NUZOadeOxrn77aPfMII1dnDQlPkTbPa5SqOZKc3y4A9NadnicGipgAO36CtLAa6xs1MT6IrjY/t61ez1foTMxJN6B2Vuec5GFDM8V9Tnma8+wQDoZRY/8SDFBEAJQehNErRWgBaSGuyz/2wRv6510Yg+UY0DLCGyTys5SvcMwfCfRSSzfymyZKS30vZBCHooRzJ6EEJOlW7Hk1XXL+WfioJHlLTzwNBXtYSyk94TOEk0MMW5gEMbLeRXLi6uOaCooYj0x8YdsB8LUqnTdFO8D/bxcrDmrQoRSR+7mr+LDVQYrBaKD5OzDBpDa9StzYl+aL3nrFcvjQmZ8Ay1w,iv:BbpIHvr1n8efHw9jgtjDSfdORYulW7EyAh/JP11gNzc=,tag:jEwBB4d2NBucOnFQ4kVIVw==,type:str]
type: kubernetes.io/dockerconfigjson
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14qjsyp5phs3ar2epq4rve57sdc08pj3w9ayvgmntj4pwd6q8ncestmxgrz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvMjM4MjZFS08vNktuNFZa
            Z0V2cVZTVXg1RWdHYzZCMVdEWUNiU2ozT2pVCmpqMFVkK0I1WHpjamVpcnhReHAz
            c1RaNkFoUjBtVWNQemJEdy9NYlAxRm8KLS0tIGNaSnlaVVpEbzRHYnFrL2hMbkNY
            SHpsdTRiY2VwVUlad1NsYnB4cjJlZWcK6u3Pk/pOF9XNhkrfsn8nN96wB9VKB0nJ
            3iw2ePYNX3n6Bb0By/ZlT5s9SoGf5lwx7T6D1+uOe6sUYzgOZ2durw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-01T01:20:28Z"
    mac: ENC[AES256_GCM,data:2FGJ7PxVIG/7QCMg34xYg90q7dKhPpPupJJcCxWs9gJbYEMLEtEHHScc2PmvSf2A4y8aidAH/qCA+IuDZqrv0NnQi6G1Lo/gei55W+sQUne/TvIDCxefWUaokLhzpmZSfeUTaxDcx0NJh3ATeJN7EI4l2gwUwzBvVyWK42gMsy8=,iv:9AK+9SMJ9L54QXMDakcMypwSgVblKk/uGJKs/dA2/nE=,tag:JcQSW96ZIKZ3ohVm4N3ROA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
