---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: komodorio
  namespace: flux-system
spec:
  interval: 1m
  url: https://helm-charts.komodor.io

---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: k8s-watcher
  namespace: flux-system
spec:
  interval: 1m
  chart:
    spec:
      chart: k8s-watcher
      sourceRef:
        kind: HelmRepository
        name: komodorio
        namespace: flux-system
      version: '*' # Use specific chart version if needed, otherwise it picks the latest
  values:
    secretRef:
      name: komodor-secret
    watcher:
      clusterName: default
      enableAgentTaskExecution: true
      allowReadingPodLogs: true
  timeout: 90s
  install:
    createNamespace: true # This will create namespace if not present
  upgrade:
    remediation:
      retries: 2 # This is optional and represents how many times Helm should retry installing/upgrading
