apiVersion: v1
kind: Secret
metadata:
    name: komodor-secret
    namespace: flux-system
type: Opaque
stringData:
    apiKey: ENC[AES256_GCM,data:bn+c5ARSF8HT7mrp5oDphPsfKAcxuAPBRBNE6xzAAZzfunhv,iv:7YsJS+TdMl4E9Cfhwe2LdWyunqnaFGAi0X/H0uzrkZg=,tag:iRS3653VWZn/XGa0NoGDiw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14qjsyp5phs3ar2epq4rve57sdc08pj3w9ayvgmntj4pwd6q8ncestmxgrz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvVUFuVjlSUm9GWHpvUTRF
            WWVjSWlJK2lJNi91dXBYNTk3b0NJK1dSWTA4CkQxRVlhQ1VxN1B2WWtscHF5ODYv
            OXFBdDFMOVYveW1RK2E1YlBtbjA1QXMKLS0tIERsY1JCYjBjejlkaExoNlo4WXpk
            ZXdMYjlrd3o3YVpzR3h0WDBSTHdwVkUKvBaqx0sNWdjuE3z91HTh58jvzq88u2QG
            M10kLh1ntx/8oR42ZBccn+GvkkSd2jo3zYc46FVCxLDTreu6Sse4Vw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-08-10T02:54:08Z"
    mac: ENC[AES256_GCM,data:7fvhYBYE5dSmF1XajwpSzpfIotRcGI1TJXzBgvijvJKP9WmwU7ye4+hPztbB2RK4obY+0G+VMlSwLiudKXBCijO+ngviINaeZ2kgPejgEL6oBk7e9utGivjxk44VmQEqDbh8TwwC1ds6yzZXqWmfFQAYGcGog/RsntLfnS3+4Us=,iv:AsvkVxc8MFfPChh1GFsl3XxxgxsS0BAgTZxqSlTgrqw=,tag:jm27SmJ4F3BpjSEA+IBleg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
