apiVersion: v1
kind: Secret
metadata:
    name: komodor-secret
    namespace: flux-system
type: Opaque
data:
    apiKey: ENC[AES256_GCM,data:vM9OxpjLHSEwGUgehgUq3m26twypNlzf50EpPGVVH3I2mP5k,iv:sd1uRC2vUUHB+yId5mqyHGmHtdkAM1t3ffVWgYlD4zk=,tag:YLp3TtIWHE8fdcdAPRR+FQ==,type:str]
    watcher:
        clusterName: ENC[AES256_GCM,data:WmNfaPT7/g==,iv:XSGPhdI66XmCqcK++lO5LAJj9KRIxg0LxD+U3qYhXPU=,tag:yhocptE4e54CT/VB3eyb/Q==,type:str]
        enableAgentTaskExecution: ENC[AES256_GCM,data:HFHOag==,iv:L8aCSoIBE1AnsF7gH2JxatwfheYggN/6eYYwtfbzk/w=,tag:KXlFzkifpGqmeHgXdqAtow==,type:bool]
        allowReadingPodLogs: ENC[AES256_GCM,data:AqczQw==,iv:6PSDuS8aHd2fXrMOwmHYAK44Y4IOfy9KlQMczpFiS7w=,tag:OTq+DTux1V2OSyxt05bSiQ==,type:bool]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14qjsyp5phs3ar2epq4rve57sdc08pj3w9ayvgmntj4pwd6q8ncestmxgrz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzaUFoOXNVSDlxUjBiaHN5
            V0prTzFBZ0QzZ1lOcCtXVGVDcEsxSmZDOVJzCmE3cGdwWGdJQmY0Q0txZk8wczRT
            bGViTlhyeWxaRm5rQjlTZk9mY0NIR28KLS0tIFhNR1krbzU0V0ZXcmhwWVl5ajdS
            R21URmtYS21iSUlvMFB6ZVBXUU55OEUK0IZsg2UsHsVguSsTkdkiUJ+ARv8qlGPQ
            zXxc7Oa9XZ4JPVInFQDcE+14dJIml2uTcBGRdKTw82tKxf6WEgw8gQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-08-10T02:47:17Z"
    mac: ENC[AES256_GCM,data:J31LOfrqw6sboOyswI1NPjkHfUbJR1d9NZngioBr7dgvi6oSRtGLX59PIWVRpbBdfoAJh8ADF4HJ9kYUQvBg4yxdjh7FbRrUDnv9h3V05fOgMVcA8OtS11GrpPsx+WZPKROlBQgSrzUw3Dns1aSKTGELhUVDz264ahvLfvhc8lY=,iv:jCVbS6yaIEygXT27K8Optf3mCzfNndLdu4Zt0k8V1UU=,tag:EuTFe9zszaVEL35hKarRTA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
