apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
    namespace: networking
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:Q4Hc5SCOZvP+269ShDeBzNToAeeOUyNRoCPK2XnGjsCNwt9z,iv:StHjSkDnUl785YH12lcygBWE20N8Q4nJcckRjV2XFiE=,tag:hF/yBmW7GGvNDsYpZ9D2HQ==,type:str]
    credentials.json: ENC[AES256_GCM,data:fpFAoh+/3RcsDuz5Ex12swWQwcOiQ+LBx4+uqrz1orndowIGuyNcYtZHlF11nc1PQUhz9jvvy50mIm9RnbSVj1zUkg6U+fNvmiVZeU1rEAnJMxZfl8kUGWoGAtZ6MZKh5AFpCJ5fKWXe9GBaL0qMxLZI0PxIPy3fJFk7pkNYiek2em5syEhl9DOlDgFO0X9h2TSbn4u472hehgA5DkwDrcj5kKsyp/TXhyO01Gfr6g==,iv:bxRtG8ReDDSNNGGYN9peXcVhyEjh3BAYuND4+ojtGw8=,tag:T/vRgg1hAPTz3EyyIoK+0w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14qjsyp5phs3ar2epq4rve57sdc08pj3w9ayvgmntj4pwd6q8ncestmxgrz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXWVdwWjhubGJ2RHRQR1hY
            bWEyeVJEblJkYkptZ0xnRmYyRjlTS0tTMDFJCjBUTXl4VUZqNFFrYmZZbmZVbHNh
            TitiQWp3b0JjNk92OUp1cFdxVFN0RW8KLS0tICs1UENRa3FvUHRQY0NRWlh1Wnlr
            SEFwdkhuM3FIYjRXdllCZmJFSGtWV28KK27/c3yvVzVHvV4oBZVLSMp7jbyUMO/E
            JXduxAH21ptbeS7PvLT/NSP11ErGMlwTwwohKJCUKHXuHJg43JgUUA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-29T02:13:21Z"
    mac: ENC[AES256_GCM,data:yDZ5wtdDrQaOXDLV8JfbiE7jX9gmIhydp9AhUR+p312iMvyYkEfaZDjpcP0V4KoarWdQT8+97OC7RRsF97L/e3cYsfnOey1PqWvV8GnaAYJKgfRg7QEHGC8XXOSq5WkG3rNOrV+LtgDg9v9Cu0zjdA8qlcopVBirJY2qc8WL/ek=,iv:RL+bGmh/LFim/XqyMBw3JT/5HTNbgXhJvVWlSNPTSSo=,tag:8WU0Mo1IpqlH7dXetIBeYQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
