---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: renovate
  namespace: &namespace kube-system
spec:
  interval: 5m
  chart:
    spec:
      chart: renovate
      version: 36.42.1
      sourceRef:
        kind: HelmRepository
        name: renovate-charts
        namespace: flux-system
      interval: 5m
  targetNamespace: kube-system
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    fullnameOverride: *namespace
