---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: choice-marketing-www
  namespace: dev-stage
spec:
  path: ./kubernetes/apps/dev-stage/choice-marketing-www/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: false
  interval: 30m
  retryInterval: 1m
  timeout: 5m
